### ISSUE TITLE
Move from GPLv3 to Apache 2.0 or MIT License

### ISSUE THREAD

**Issue by breadtk** [dzonerzy/PyJFuzz#1]
Hello,

I wanted to ask if you would be willing to move your project away from GPLv3 license to a more permissive and non-restrictive license like [MIT](http://choosealicense.com/licenses/mit/) or [Apache 2.0](http://choosealicense.com/licenses/apache-2.0/) licenses. Github has put together a great license comparison website called [ChooseALicense.com](http://choosealicense.com/) if you would like to make a more informed decision.

**Comment by dzonerzy** [comment]
Sure you're right! i'll put MIT license.

**Comment by dzonerzy** [comment]
Should be ok now.
